import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
const js=fs.readFileSync(new URL('../openwrt/main.js',import.meta.url),'utf8');
const c=vm.createContext({Intl,E:(tag,attrs,children)=>({tag,attrs,children}),_:text=>text});
for (const name of ['subscriptionTagMatches','isSubscriptionTagFiltered','getEffectiveSubscriptionTags','getSubscriptionTagChoices','renderSubscriptionTagPicker','buildSubscriptionSectionChanges']) {
  vm.runInContext(js.match(new RegExp(`function ${name}\\([\\s\\S]*?\\n}`))[0],c);
}
const ordinary={name:'🇫🇮 Финляндия',supported:true};
const gaming={name:'🇫🇮 Финляндия [🎮 Игровой]',supported:true};
const otherGaming={name:'🇺🇸 США [🎮 Игровой]',supported:true};
assert.equal(c.isSubscriptionTagFiltered(ordinary,['@prefix:FI'],['@game:only']),true,'gaming-only must exclude ordinary nodes');
assert.equal(c.isSubscriptionTagFiltered(gaming,['@prefix:FI'],['@game:only']),false);
assert.equal(c.isSubscriptionTagFiltered(otherGaming,['@prefix:FI'],['@game:only']),true,'game rule must not bypass countries');
assert.equal(c.isSubscriptionTagFiltered(gaming,[],['@game:exclude']),true);
assert.equal(c.isSubscriptionTagFiltered(ordinary,[],['@game:exclude']),false);
assert.equal(c.isSubscriptionTagFiltered({name:'FI Hysteria2 🎮'},[],['@game:only']),true,'protocol and emoji alone are not gaming proof');
assert.equal(c.isSubscriptionTagFiltered(gaming,['@prefix:FI'],['@game:only','@prefix:FI']),true,'country exclusion retains priority');
assert.equal(c.isSubscriptionTagFiltered(gaming,[],['@game:only','@game:exclude']),true,'conflicting rules fail closed');
const section={code:'main',displayName:'main',selectionMode:'auto',includeTags:['@prefix:FI'],excludeTags:['@prefix:US','@game:only','old*'],items:[ordinary,gaming,otherGaming]};
assert.ok(!c.getSubscriptionTagChoices(section,section.excludeTags).some(x=>x.value.startsWith('@game:')),'game rules must not clutter the country picker');
c.subscriptionTagPickerOpen={};
let changed;
const walk=node=>Array.isArray(node)?node.flatMap(walk):!node||typeof node!=='object'?[]:[node,...walk(node.children)];
const countryPicker=c.renderSubscriptionTagPicker(section,{},'exclude',false,(...args)=>changed=args);
walk(countryPicker).find(x=>x.tag==='input'&&x.attrs.value==='@prefix:US').attrs.change({target:{checked:false}});
assert.deepEqual(JSON.parse(JSON.stringify(changed)),['main',{id:'tags:exclude',enabled:section.excludeTags},['@game:only','old*']],'country edits must preserve game policy');
Object.assign(c,{getTagFilterPreview:()=>({enabled:1}),getSourceGroups:()=>[],isSubscriptionSectionCollapsed:()=>false,getSectionCollapsedSummary:()=>'',getEffectiveSelectionMode:()=> 'auto',renderEmptyState:()=>null});
vm.runInContext(js.match(/function renderSection\([\s\S]*?\n}(?=\r?\n)/)[0],c);
const render=(pending={},disabled=false)=>c.renderSection({section,pendingChanges:pending,applying:disabled,onToggle:(...args)=>changed=args,sourceActions:{}});
const select=walk(render()).find(x=>x.tag==='select'&&x.attrs['aria-label']==='Тип узлов');
assert.ok(select,'separate game filter must be visible');
assert.equal(walk(select).find(x=>x.tag==='option'&&x.attrs.selected)?.attrs.value,'gaming');
select.attrs.change({target:{value:'non-gaming'}});
assert.deepEqual(JSON.parse(JSON.stringify(changed)),['main',{id:'tags:exclude',enabled:section.excludeTags},['@prefix:US','old*','@game:exclude']]);
const payload=c.buildSubscriptionSectionChanges(changed[0],[{id:changed[1].id,enabled:changed[2]}]);
assert.deepEqual(Array.from(payload.excludeTags),['@prefix:US','old*','@game:exclude'],'same existing transaction persists game choice');
select.attrs.change({target:{value:'all'}});
assert.deepEqual(Array.from(changed[2]),['@prefix:US','old*'],'All removes only game policy');
const pending={'main:tags:exclude':['@prefix:US','@game:exclude']};
const draftSelect=walk(render(pending)).find(x=>x.tag==='select'&&x.attrs['aria-label']==='Тип узлов');
assert.equal(walk(draftSelect).find(x=>x.tag==='option'&&x.attrs.selected)?.attrs.value,'non-gaming','draft mode survives rerender');
draftSelect.attrs.change({target:{value:'gaming'}});
assert.deepEqual(Array.from(changed[2]),['@prefix:US','@game:only']);
assert.equal(walk(render({},true)).find(x=>x.tag==='select'&&x.attrs['aria-label']==='Тип узлов').attrs.disabled,'disabled');
const conflict=walk(render({'main:tags:exclude':['@game:only','@game:exclude']})).find(x=>x.tag==='select'&&x.attrs['aria-label']==='Тип узлов');
assert.equal(walk(conflict).find(x=>x.tag==='option'&&x.attrs.selected)?.attrs.value,'conflict');
console.log('PASS: independent game/country filters, drafts, transaction and preserved custom rules');
